# Generated by Django 4.0.6 on 2022-08-03 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tasks', '0003_task_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_members', to='users.profile'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.profile'),
        ),
    ]
